name: User fieldtrack Backend Production

on:

  push:

    branches:

      - develop

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository

        uses: actions/checkout@v4

      - name: Deploy to Development Server

        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.SERVER_IP }}

          username: ${{ secrets.SERVER_USERNAME }}

          password: ${{ secrets.SERVER_PASSWORD }}

          script: |

            echo "Connecting to the Development Server..."

            cd /home/node/user-fieldtracking-backend-prod

            echo "Loading NVM..."

            export NVM_DIR="$HOME/.nvm"

            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "Using Node.js version 20..."

            nvm use 20

            echo "Pulling latest changes..."

            git checkout develop

            git pull origin develop

            echo "Installing dependencies..."

            npm install || { echo "npm install failed"; exit 1; }

            echo "Building the project..."

            npm run build || { echo "Build failed"; exit 1; }

            echo "Restarting the application using PM2..."

            export PATH=$HOME/.nvm/versions/node/v20/bin:$PATH

            pm2 restart 3 --silent || { echo "PM2 restart failed"; exit 1; }

            echo "Development Deployment Completed Successfully!"
 
